[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "icbuilder"
version = "0.1"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["icbuilder"]
